# Generated by Django 5.0.14 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("admin_emails", models.TextField(blank=True, null=True)),
                ("last_google_access_token", models.TextField(blank=True, null=True)),
                (
                    "last_google_access_token_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(max_length=50)),
                ("login_at", models.DateTimeField()),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(default="EMPLOYEE", max_length=50)),
                ("photo_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
