# Generated by Django 5.0.14 on 2026-07-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_seed_default_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
