# Generated by Django 5.0.14 on 2026-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_preserve_existing_module_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='member_employees', to='authentication.department'),
        ),
    ]
