import React, { useEffect, useState } from 'react';
import { ArrowLeft, BookOpen, CalendarDays, CheckCircle2, ClipboardList, ExternalLink, GraduationCap, Handshake, LogIn, Plus, Search, Users, X } from 'lucide-react';

type Tab = 'calendar' | 'sessions' | 'partners' | 'survey' | 'materials';
type Mode = 'week' | 'month' | 'quarter' | 'year';
type Modal = 'session' | 'partner' | 'material' | 'survey' | null;
type Partner = {id:number;name:string;address:string;contact_person:string;phone:string;email:string;contract_start:string;contract_end:string;training_content:string;planned_sessions:number;completed_sessions:number;notes:string};
type Session = {id:number;title:string;date:string;start_time?:string|null;end_time?:string|null;partner:string;partner_id?:number|null;partner_name?:string;category:string;attendees:number;location:string;status:'planned'|'completed'|'cancelled';notes:string;has_materials:boolean};
type Material = {id:number;title:string;file_url:string;external_url:string;file_name:string;file_type:string;session?:number|null;session_name?:string;partner?:number|null;partner_name?:string;notes:string};
type Survey = {id:number;title:string;form_type:'end_session'|'end_course';session?:number|null;session_name?:string;partner?:number|null;partner_name?:string;notes:string};
const categories=['Triển khai BNDC','Ứng dụng AI trong quản lý hành chính','Ứng dụng AI trong giảng dạy','Đào tạo lớp học số'];
const tabs:{id:Tab;label:string;icon:React.ElementType}[]=[{id:'calendar',label:'Lịch tập huấn',icon:CalendarDays},{id:'sessions',label:'Danh sách buổi',icon:ClipboardList},{id:'partners',label:'Đối tác',icon:Handshake},{id:'survey',label:'Khảo sát',icon:Users},{id:'materials',label:'Tài liệu',icon:BookOpen}];
const today=()=>new Date().toISOString().slice(0,10);
const showDate=(v?:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString('vi-VN'):'—';
const showTime=(s:Session)=>[s.start_time?.slice(0,5),s.end_time?.slice(0,5)].filter(Boolean).join(' – ')||'Chưa đặt giờ';
const status:{[key:string]:string}={planned:'Đã lên lịch',completed:'Đã thực hiện',cancelled:'Đã hủy'};
function currentRoute(){const p=location.pathname.replace(/^\/+|\/+$/g,'').split('/');const tab=(tabs.some(x=>x.id===p[1])?p[1]:'calendar') as Tab;return {tab,partnerId:tab==='partners'&&p[2]?Number(p[2]):null}}
const pathFor=(tab:Tab,id?:number|null)=>tab==='calendar'?'/digital-training':tab==='partners'&&id?`/digital-training/partners/${id}`:`/digital-training/${tab}`;
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="ft-dialog-backdrop fixed inset-0 z-50 grid place-items-center p-4"><div className="ft-dialog-panel max-h-[calc(100vh-2rem)] w-full max-w-2xl overflow-y-auto bg-white p-6"><div className="mb-5 flex justify-between gap-3"><h2 className="text-xl font-extrabold">{title}</h2><button onClick={onClose}><X className="h-5 w-5"/></button></div>{children}</div></div>}
function Input({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label><span className="mb-1 block text-sm font-bold">{label}</span><input {...props} className="w-full rounded-lg border border-slate-300 px-3 py-2"/></label>}
function Calendar({mode,sessions,onPick}:{mode:Mode;sessions:Session[];onPick:(d:string)=>void}) {
  const [cursor, setCursor] = useState(() => new Date());
  const iso = (value: Date) => new Date(value.getFullYear(), value.getMonth(), value.getDate()).toISOString().slice(0,10);
  const startOfWeek = (value: Date) => { const date = new Date(value.getFullYear(), value.getMonth(), value.getDate()); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; };
  const todayKey = today();
  const shift = (amount: number) => setCursor(value => mode==='week' ? new Date(value.getFullYear(), value.getMonth(), value.getDate()+amount*7) : new Date(value.getFullYear(), value.getMonth()+amount, 1));
  const rangeTitle = mode==='week' ? (() => { const first=startOfWeek(cursor), last=new Date(first.getFullYear(),first.getMonth(),first.getDate()+6); return `${first.toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit'})} – ${last.toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'})}`; })() : cursor.toLocaleDateString('vi-VN',{month:'long',year:'numeric'});
  const events = (date: Date, hour?: number) => sessions.filter(item => item.date===iso(date) && (hour===undefined || !item.start_time || Number(item.start_time.slice(0,2))===hour));
  if(mode==='quarter'||mode==='year') {
    const amount=mode==='quarter'?3:12;
    return <div className={`grid gap-3 ${mode==='year'?'sm:grid-cols-2 xl:grid-cols-3':'md:grid-cols-3'}`}>{Array.from({length:amount},(_,index)=>{const month=new Date(cursor.getFullYear(),cursor.getMonth()+index,1), rows=sessions.filter(item=>{const date=new Date(`${item.date}T00:00:00`);return date.getMonth()===month.getMonth()&&date.getFullYear()===month.getFullYear()});return <button key={month.toISOString()} onClick={()=>onPick(iso(month))} className="rounded-xl border border-sky-100 bg-white p-4 text-left shadow-sm transition hover:border-sky-300 hover:bg-sky-50"><b className="text-slate-800">{month.toLocaleDateString('vi-VN',{month:'long',year:'numeric'})}</b>{rows.length?<div className="mt-3 space-y-1">{rows.map(item=><span key={item.id} className="block truncate rounded bg-sky-100 px-2 py-1.5 text-xs font-bold text-sky-800">{showDate(item.date)} · {item.title}</span>)}</div>:<span className="mt-4 block text-xs text-slate-400">Bấm để tạo lịch</span>}</button>})}</div>
  }
  if(mode==='month') {
    const first=new Date(cursor.getFullYear(),cursor.getMonth(),1), offset=(first.getDay()+6)%7, total=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();
    const dates=Array.from({length:Math.ceil((offset+total)/7)*7},(_,index)=>index<offset||index>=offset+total?null:new Date(cursor.getFullYear(),cursor.getMonth(),index-offset+1));
    return <div className="dt-calendar"><div className="dt-calendar-toolbar"><div className="flex items-center gap-2"><button onClick={()=>setCursor(new Date())}>Hôm nay</button><button aria-label="Tháng trước" onClick={()=>shift(-1)}>‹</button><button aria-label="Tháng sau" onClick={()=>shift(1)}>›</button></div><b className="text-sm text-slate-800">{rangeTitle}</b></div><div className="grid grid-cols-7">{['T2','T3','T4','T5','T6','T7','CN'].map(label=><div key={label} className="border-b border-sky-100 p-2 text-center text-xs font-bold text-slate-500">{label}</div>)}{dates.map((date,index)=>date?<button key={iso(date)} onClick={()=>onPick(iso(date))} className="min-h-28 border-b border-r border-sky-100 p-2 text-left transition hover:bg-sky-50"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${iso(date)===todayKey?'bg-sky-600 text-white':'text-slate-600'}`}>{date.getDate()}</span>{events(date).slice(0,3).map(item=><span key={item.id} className={`mt-1 block truncate rounded px-1.5 py-1 text-[10px] font-bold ${item.status==='completed'?'bg-emerald-100 text-emerald-800':item.status==='cancelled'?'bg-rose-100 text-rose-700':'bg-sky-100 text-sky-800'}`}>{showTime(item)} · {item.title}</span>)}</button>:<div key={index} className="min-h-28 border-b border-r border-sky-50 bg-slate-50/50"/>)}</div></div>
  }
  const first=startOfWeek(cursor), dates=Array.from({length:7},(_,index)=>new Date(first.getFullYear(),first.getMonth(),first.getDate()+index)), hours=Array.from({length:13},(_,index)=>index+8);
  return <div className="dt-calendar"><div className="dt-calendar-toolbar"><div className="flex items-center gap-2"><button onClick={()=>setCursor(new Date())}>Hôm nay</button><button aria-label="Tuần trước" onClick={()=>shift(-1)}>‹</button><button aria-label="Tuần sau" onClick={()=>shift(1)}>›</button></div><b className="text-sm text-slate-800">{rangeTitle}</b></div><div className="dt-calendar-scroll"><div className="dt-calendar-week"><div className="dt-calendar-head"/>{dates.map(date=><div key={iso(date)} className={`dt-calendar-head ${iso(date)===todayKey?'is-today':''}`}>{date.toLocaleDateString('vi-VN',{weekday:'short'})}<strong>{date.getDate()}</strong></div>)}{hours.flatMap(hour=>[<div key={`hour-${hour}`} className="dt-calendar-hour">{String(hour).padStart(2,'0')}:00</div>,...dates.map(date=><button key={`${iso(date)}-${hour}`} onClick={()=>onPick(iso(date))} className="dt-calendar-cell">{events(date,hour).map(item=><span key={item.id} className={`dt-calendar-event ${item.status==='completed'?'is-completed':item.status==='cancelled'?'is-cancelled':''}`}>{showTime(item)} · {item.title}</span>)}</button>)])}</div></div></div>
}
export default function DigitalTraining({onBackToWorkspace,onAccountClick,isGuest,userName,idToken=''}:{onBackToWorkspace:()=>void;onAccountClick:()=>void;isGuest:boolean;userName?:string|null;idToken?:string}){
 const route=currentRoute(),[tab,setTab]=useState<Tab>(route.tab),[selected,setSelected]=useState<number|null>(route.partnerId),[sessions,setSessions]=useState<Session[]>([]),[partners,setPartners]=useState<Partner[]>([]),[materials,setMaterials]=useState<Material[]>([]),[surveys,setSurveys]=useState<Survey[]>([]),[mode,setMode]=useState<Mode>('week'),[modal,setModal]=useState<Modal>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[file,setFile]=useState<File|null>(null);
 const [sd,setSd]=useState({title:'',date:today(),start_time:'',end_time:'',partner_id:'',category:categories[0],attendees:'0',location:'',status:'planned',notes:''});const [pd,setPd]=useState({name:'',address:'',contact_person:'',phone:'',email:'',contract_start:'',contract_end:'',training_content:'',planned_sessions:'0',notes:''});const [md,setMd]=useState({title:'',external_url:'',session:'',partner:'',notes:''});const [sv,setSv]=useState({title:'',form_type:'end_session',session:'',partner:'',notes:''});
 const auth=()=>idToken?{Authorization:`Bearer ${idToken}`}:{}, load=async()=>{setLoading(true);try{const list=await Promise.all(['sessions','partners','materials','surveys'].map(async x=>{const r=await fetch(`/api/digital-training/${x}`,{headers:auth()});if(!r.ok)throw Error('Không thể tải dữ liệu Đào tạo số.');return r.json()}));setSessions(list[0]);setPartners(list[1]);setMaterials(list[2]);setSurveys(list[3])}catch(e:any){setNotice(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[idToken]);useEffect(()=>{const h=()=>{const r=currentRoute();setTab(r.tab);setSelected(r.partnerId)};addEventListener('popstate',h);return()=>removeEventListener('popstate',h)},[]);
 const go=(t:Tab,id?:number|null)=>{setTab(t);setSelected(id||null);history.pushState(null,'',pathFor(t,id))}, can=()=>{if(!idToken||isGuest){setNotice('Vui lòng đăng nhập bằng tài khoản quản lý để tạo dữ liệu.');return false}return true}, post=async(url:string,data:any)=>{const r=await fetch(`/api/digital-training/${url}`,{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify(data)}),b=await r.json();if(!r.ok)throw Error(b.error||'Không thể lưu dữ liệu.');return b}, pick=(date:string)=>{setSd({...sd,title:'',date});setModal('session')};
 const saveSession=async(e:React.FormEvent)=>{e.preventDefault();if(!can())return;try{await post('sessions',{...sd,partner_id:sd.partner_id?Number(sd.partner_id):null,attendees:Number(sd.attendees)});setModal(null);await load();setNotice('Đã tạo buổi tập huấn.')}catch(e:any){setNotice(e.message)}};
 const savePartner=async(e:React.FormEvent)=>{e.preventDefault();if(!can())return;try{await post('partners',{...pd,planned_sessions:Number(pd.planned_sessions)});setModal(null);await load();setNotice('Đã thêm đối tác mới.')}catch(e:any){setNotice(e.message)}};
 const saveSurvey=async(e:React.FormEvent)=>{e.preventDefault();if(!can())return;try{await post('surveys',{...sv,session:sv.session?Number(sv.session):null,partner:sv.partner?Number(sv.partner):null});setModal(null);await load();setNotice('Đã tạo form khảo sát.')}catch(e:any){setNotice(e.message)}};
 const saveMaterial=async(e:React.FormEvent)=>{e.preventDefault();if(!can())return;try{const b=new FormData();Object.entries(md).forEach(([k,v])=>{if((k==='session'||k==='partner')&&!v)return;b.append(k,v)});if(file)b.append('file',file);const r=await fetch('/api/digital-training/materials',{method:'POST',headers:auth(),body:b}),d=await r.json();if(!r.ok)throw Error(d.error||'Không thể lưu tài liệu.');setModal(null);setFile(null);await load();setNotice('Đã thêm tài liệu.')}catch(e:any){setNotice(e.message)}};
 const partner=partners.find(x=>x.id===selected), filtered=sessions.filter(x=>(!query||[x.title,x.partner,x.category,x.location].join(' ').toLowerCase().includes(query.toLowerCase()))&&(!filter||x.status===filter));
 return <div className="ft-module-shell flex min-h-screen text-slate-800"><aside className="ft-module-sidebar sticky top-0 hidden h-screen w-64 shrink-0 flex-col border-r lg:flex"><div className="ft-sidebar-brand flex items-center gap-3 border-b p-5"><img src="/logo.png" className="h-8 object-contain"/><div className="border-l pl-3"><b>Fermat</b><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-cyan-600">Đào tạo số</p></div></div><div className="p-4"><button onClick={onBackToWorkspace} className="ft-sidebar-back flex w-full items-center gap-2 rounded-xl border px-3 py-2.5 text-xs font-bold"><ArrowLeft className="h-4 w-4"/>Quay lại Workspace</button></div><nav className="flex-1 space-y-1 px-4">{tabs.map(x=>{const Icon=x.icon;return <button key={x.id} onClick={()=>go(x.id)} className={`flex w-full items-center gap-3 rounded-xl px-3.5 py-2.5 text-left text-xs font-bold ${tab===x.id?'ft-nav-item ft-nav-item-active':'ft-nav-item'}`}><Icon className="h-4 w-4"/>{x.label}</button>})}</nav><div className="border-t p-4"><button onClick={onAccountClick} className="flex w-full justify-center gap-2 rounded-xl bg-cyan-600 px-3 py-2.5 text-xs font-bold text-white">{isGuest&&<LogIn className="h-4 w-4"/>}{isGuest?'Đăng nhập':userName||'Tài khoản'}</button></div></aside><main className="min-w-0 flex-1"><header className="ft-module-header flex h-16 items-center justify-between border-b px-5 md:px-8"><div><p className="text-xs font-bold uppercase text-cyan-600">Đào tạo số</p><h1 className="text-lg font-extrabold">{partner?partner.name:tabs.find(x=>x.id===tab)?.label}</h1></div><button onClick={onAccountClick} className="rounded-lg border px-3 py-2 text-sm font-bold lg:hidden">{isGuest?'Đăng nhập':userName||'Tài khoản'}</button></header><div className="ft-module-content mx-auto p-5 md:p-7">
 {loading?<div className="py-20 text-center text-sm text-slate-500">Đang tải dữ liệu...</div>:<>
 {tab==='calendar'&&<section className="mt-1 rounded-2xl border border-sky-100 bg-white p-5 shadow-sm"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-sky-700">Đào tạo số</p><h2 className="mt-1 text-xl font-extrabold">Lịch tập huấn</h2><p className="mt-1 text-sm text-slate-500">Bấm vào ô lịch để tạo buổi mới; có thể xem theo tuần, tháng, quý hoặc năm.</p></div><div className="flex flex-wrap items-center gap-3"><div className="flex rounded-lg border border-sky-200 bg-sky-50 p-1">{(['week','month','quarter','year'] as Mode[]).map(x=><button key={x} onClick={()=>setMode(x)} className={`rounded px-3 py-1.5 text-xs font-bold ${mode===x?'bg-sky-600 text-white shadow-sm':'text-slate-600 hover:bg-white'}`}>{{week:'Tuần',month:'Tháng',quarter:'Quý',year:'Năm'}[x]}</button>)}</div><button onClick={()=>pick(today())} className="ft-primary"><Plus className="h-4 w-4"/>Tạo buổi tập huấn</button></div></div><Calendar mode={mode} sessions={sessions} onPick={pick}/></section>}
 {tab==='sessions'&&<section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="text-xl font-extrabold">Danh sách buổi tập huấn</h2><p className="mt-1 text-sm text-slate-500">Theo dõi thời gian, địa điểm và trạng thái thực hiện.</p></div><button onClick={()=>pick(today())} className="ft-primary"><Plus className="h-4 w-4"/>Tạo buổi tập huấn</button></div><div className="grid gap-3 border-y p-4 md:grid-cols-3"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm buổi, đối tác, địa điểm..." className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">Tất cả trạng thái</option><option value="planned">Đã lên lịch</option><option value="completed">Đã thực hiện</option><option value="cancelled">Đã hủy</option></select></div><div className="overflow-x-auto"><table className="ft-table"><thead><tr><th>Thời gian</th><th>Buổi tập huấn</th><th>Đối tác</th><th>Địa điểm</th><th>Lĩnh vực</th><th>Trạng thái</th><th>Tham gia</th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td><b>{showDate(x.date)}</b><span className="block text-xs text-slate-500">{showTime(x)}</span></td><td><b>{x.title}</b></td><td>{x.partner_name||x.partner||'—'}</td><td>{x.location||'—'}</td><td>{x.category||'—'}</td><td><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{status[x.status]}</span></td><td>{x.attendees}</td></tr>):<tr><td colSpan={7} className="py-10 text-center text-slate-500">Chưa có buổi phù hợp.</td></tr>}</tbody></table></div></section>}
 {tab==='partners'&&!partner&&<section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap justify-between gap-3 p-5"><div><h2 className="text-xl font-extrabold">Đối tác</h2><p className="mt-1 text-sm text-slate-500">Theo dõi hợp đồng, nội dung và tiến độ tập huấn.</p></div><button onClick={()=>{setPd({name:'',address:'',contact_person:'',phone:'',email:'',contract_start:'',contract_end:'',training_content:'',planned_sessions:'0',notes:''});setModal('partner')}} className="ft-primary"><Plus className="h-4 w-4"/>Thêm đối tác mới</button></div><div className="border-y p-4"><label className="relative block max-w-xl"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Lọc theo tên, địa chỉ, nội dung..." className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm"/></label></div><div className="overflow-x-auto"><table className="ft-table"><thead><tr><th>Đối tác</th><th>Địa chỉ</th><th>Thời gian hợp đồng</th><th>Nội dung đào tạo</th><th>Số buổi</th><th>Đã thực hiện</th><th>Ghi chú</th></tr></thead><tbody>{partners.filter(x=>!query||[x.name,x.address,x.training_content].join(' ').toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id} onClick={()=>go('partners',x.id)} className="cursor-pointer hover:bg-cyan-50"><td><b>{x.name}</b><span className="block text-xs text-slate-500">{x.contact_person||'Chưa có đầu mối'}</span></td><td>{x.address||'—'}</td><td>{[x.contract_start,x.contract_end].filter(Boolean).join(' – ')||'—'}</td><td className="max-w-xs whitespace-normal">{x.training_content||'—'}</td><td>{x.planned_sessions}</td><td>{x.completed_sessions}</td><td className="max-w-xs whitespace-normal">{x.notes||'—'}</td></tr>)}</tbody></table></div></section>}
 {tab==='partners'&&partner&&<section className="mt-6"><button onClick={()=>go('partners')} className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Quay lại danh sách đối tác</button><article className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase text-cyan-600">Đối tác đào tạo</p><div className="flex flex-wrap justify-between gap-4"><div><h2 className="mt-1 text-2xl font-extrabold">{partner.name}</h2><p className="mt-2 text-sm text-slate-500">{partner.address||'Chưa cập nhật địa chỉ'}</p></div><b className="rounded-xl bg-cyan-50 px-4 py-3 text-cyan-900">{partner.completed_sessions}/{partner.planned_sessions} buổi đã thực hiện</b></div><div className="mt-5 grid gap-4 border-t pt-5 md:grid-cols-3"><p><b className="block text-xs uppercase text-slate-500">Hợp đồng</b>{[partner.contract_start,partner.contract_end].filter(Boolean).join(' – ')||'Chưa cập nhật'}</p><p><b className="block text-xs uppercase text-slate-500">Đầu mối</b>{partner.contact_person||'—'} {partner.phone&&`· ${partner.phone}`}</p><p><b className="block text-xs uppercase text-slate-500">Nội dung</b>{partner.training_content||'—'}</p></div></article><div className="mt-5 grid gap-5 xl:grid-cols-3">{[['Lịch tập huấn',sessions.filter(x=>x.partner_id===partner.id||x.partner===partner.name).map(x=>`${showDate(x.date)} · ${x.title}`)],['Phiếu khảo sát',surveys.filter(x=>x.partner===partner.id).map(x=>x.title)],['Tài liệu',materials.filter(x=>x.partner===partner.id).map(x=>x.title)]].map(([title,rows]:any)=><article key={title} className="rounded-2xl border bg-white p-5"><h3 className="font-extrabold">{title}</h3>{rows.length?<div className="mt-3 space-y-2">{rows.map((x:string)=><p key={x} className="rounded-lg bg-slate-50 p-3 text-sm">{x}</p>)}</div>:<p className="mt-3 text-sm text-slate-500">Chưa có dữ liệu.</p>}</article>)}</div></section>}
 {tab==='survey'&&<section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap justify-between gap-3 p-5"><div><h2 className="text-xl font-extrabold">Khảo sát</h2><p className="mt-1 text-sm text-slate-500">Tạo và theo dõi phiếu khảo sát; chưa hiển thị biểu đồ kết quả.</p></div><button onClick={()=>{setSv({title:'',form_type:'end_session',session:'',partner:'',notes:''});setModal('survey')}} className="ft-primary"><Plus className="h-4 w-4"/>Tạo form</button></div><div className="overflow-x-auto"><table className="ft-table"><thead><tr><th>Buổi tập huấn</th><th>Thời gian</th><th>Đối tác</th><th>Tài liệu</th><th>Phiếu khảo sát</th></tr></thead><tbody>{sessions.length?sessions.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{showDate(x.date)}<span className="block text-xs text-slate-500">{showTime(x)}</span></td><td>{x.partner_name||x.partner||'—'}</td><td className={x.has_materials?'text-emerald-700':'text-amber-700'}>{x.has_materials?'Đã có tài liệu':'Chưa có tài liệu'}</td><td>{surveys.some(y=>y.session===x.id)?surveys.filter(y=>y.session===x.id).map(y=><span className="block" key={y.id}>{y.title}</span>):<span className="dt-muted">Chưa tạo</span>}</td></tr>):<tr><td colSpan={5} className="py-10 text-center text-slate-500">Chưa có buổi tập huấn.</td></tr>}</tbody></table></div></section>}
 {tab==='materials'&&<section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap justify-between gap-3 p-5"><div><h2 className="text-xl font-extrabold">Tài liệu</h2><p className="mt-1 text-sm text-slate-500">Ưu tiên lưu link Google Drive; cũng hỗ trợ tải tài liệu, slide, bảng tính và hình ảnh.</p></div><button onClick={()=>{setMd({title:'',external_url:'',session:'',partner:'',notes:''});setFile(null);setModal('material')}} className="ft-primary"><Plus className="h-4 w-4"/>Thêm tài liệu mới</button></div><div className="overflow-x-auto"><table className="ft-table"><thead><tr><th>Tài liệu</th><th>Buổi tập huấn</th><th>Đối tác</th><th>Nguồn</th><th>Ghi chú</th></tr></thead><tbody>{materials.map(x=><tr key={x.id}><td><b>{x.title}</b><span className="block text-xs text-slate-500">{x.file_name||x.file_type||'Link Google Drive / URL'}</span></td><td>{x.session_name||'—'}</td><td>{x.partner_name||'—'}</td><td><a href={x.external_url||x.file_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-bold text-cyan-700"><ExternalLink className="h-3.5 w-3.5"/>Mở</a></td><td>{x.notes||'—'}</td></tr>)}</tbody></table></div></section>}
 </>}
 {modal==='session'&&<Dialog title="Tạo buổi tập huấn" onClose={()=>setModal(null)}><form onSubmit={saveSession} className="grid gap-4"><Input label="Tên buổi *" required value={sd.title} onChange={e=>setSd({...sd,title:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2"><Input label="Ngày *" required type="date" value={sd.date} onChange={e=>setSd({...sd,date:e.target.value})}/><label><span className="mb-1 block text-sm font-bold">Đối tác</span><select value={sd.partner_id} onChange={e=>setSd({...sd,partner_id:e.target.value})} className="w-full rounded-lg border px-3 py-2"><option value="">Chọn đối tác</option>{partners.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Input label="Bắt đầu" type="time" value={sd.start_time} onChange={e=>setSd({...sd,start_time:e.target.value})}/><Input label="Kết thúc" type="time" value={sd.end_time} onChange={e=>setSd({...sd,end_time:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-bold">Lĩnh vực</span><select value={sd.category} onChange={e=>setSd({...sd,category:e.target.value})} className="w-full rounded-lg border px-3 py-2">{categories.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-1 block text-sm font-bold">Trạng thái</span><select value={sd.status} onChange={e=>setSd({...sd,status:e.target.value})} className="w-full rounded-lg border px-3 py-2"><option value="planned">Đã lên lịch</option><option value="completed">Đã thực hiện</option><option value="cancelled">Đã hủy</option></select></label><Input label="Địa điểm / Link" value={sd.location} onChange={e=>setSd({...sd,location:e.target.value})}/><Input label="Số người tham gia" type="number" min="0" value={sd.attendees} onChange={e=>setSd({...sd,attendees:e.target.value})}/></div><label><span className="mb-1 block text-sm font-bold">Ghi chú</span><textarea value={sd.notes} onChange={e=>setSd({...sd,notes:e.target.value})} className="min-h-20 w-full rounded-lg border px-3 py-2"/></label><div className="flex justify-end gap-3"><button type="button" onClick={()=>setModal(null)} className="rounded-lg border px-4 py-2 text-sm font-bold">Hủy</button><button className="ft-primary">Tạo buổi tập huấn</button></div></form></Dialog>}
 {modal==='partner'&&<Dialog title="Thêm đối tác mới" onClose={()=>setModal(null)}><form onSubmit={savePartner} className="grid gap-4"><Input label="Tên đối tác *" required value={pd.name} onChange={e=>setPd({...pd,name:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2"><Input label="Hợp đồng từ" value={pd.contract_start} onChange={e=>setPd({...pd,contract_start:e.target.value})} placeholder="DD/MM/YYYY hoặc MM/YYYY"/><Input label="Đến" value={pd.contract_end} onChange={e=>setPd({...pd,contract_end:e.target.value})} placeholder="DD/MM/YYYY hoặc MM/YYYY"/><Input label="Địa chỉ" value={pd.address} onChange={e=>setPd({...pd,address:e.target.value})}/><Input label="Đầu mối" value={pd.contact_person} onChange={e=>setPd({...pd,contact_person:e.target.value})}/><Input label="Điện thoại" value={pd.phone} onChange={e=>setPd({...pd,phone:e.target.value})}/><Input label="Email" type="email" value={pd.email} onChange={e=>setPd({...pd,email:e.target.value})}/><Input label="Số buổi dự kiến" type="number" min="0" value={pd.planned_sessions} onChange={e=>setPd({...pd,planned_sessions:e.target.value})}/></div><label><span className="mb-1 block text-sm font-bold">Nội dung đào tạo</span><textarea value={pd.training_content} onChange={e=>setPd({...pd,training_content:e.target.value})} className="min-h-20 w-full rounded-lg border px-3 py-2"/></label><label><span className="mb-1 block text-sm font-bold">Ghi chú</span><textarea value={pd.notes} onChange={e=>setPd({...pd,notes:e.target.value})} className="min-h-16 w-full rounded-lg border px-3 py-2"/></label><div className="flex justify-end gap-3"><button type="button" onClick={()=>setModal(null)} className="rounded-lg border px-4 py-2 text-sm font-bold">Hủy</button><button className="ft-primary">Thêm đối tác</button></div></form></Dialog>}
 {modal==='material'&&<Dialog title="Thêm tài liệu mới" onClose={()=>setModal(null)}><form onSubmit={saveMaterial} className="grid gap-4"><p className="rounded-lg bg-cyan-50 p-3 text-sm text-cyan-900">Ưu tiên dán link Google Drive, Google Docs hoặc Google Sheets. Hệ thống cũng nhận PDF, Word, PowerPoint, Excel, ảnh và các tệp tài liệu phổ biến.</p><Input label="Tên tài liệu *" required value={md.title} onChange={e=>setMd({...md,title:e.target.value})}/><Input label="Link tài liệu" type="url" value={md.external_url} onChange={e=>setMd({...md,external_url:e.target.value})} placeholder="https://drive.google.com/..."/><label><span className="mb-1 block text-sm font-bold">Hoặc tải file lên</span><input type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.csv,.txt,.rtf,.odt,.ods,.odp,.jpg,.jpeg,.png,.gif,.webp" onChange={e=>setFile(e.target.files?.[0]||null)} className="w-full rounded-lg border p-2 text-sm"/></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-bold">Buổi tập huấn</span><select value={md.session} onChange={e=>setMd({...md,session:e.target.value})} className="w-full rounded-lg border px-3 py-2"><option value="">Không gắn buổi cụ thể</option>{sessions.map(x=><option key={x.id} value={x.id}>{showDate(x.date)} · {x.title}</option>)}</select></label><label><span className="mb-1 block text-sm font-bold">Đối tác</span><select value={md.partner} onChange={e=>setMd({...md,partner:e.target.value})} className="w-full rounded-lg border px-3 py-2"><option value="">Không gắn đối tác cụ thể</option>{partners.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label><span className="mb-1 block text-sm font-bold">Ghi chú</span><textarea value={md.notes} onChange={e=>setMd({...md,notes:e.target.value})} className="min-h-16 w-full rounded-lg border px-3 py-2"/></label><div className="flex justify-end gap-3"><button type="button" onClick={()=>setModal(null)} className="rounded-lg border px-4 py-2 text-sm font-bold">Hủy</button><button className="ft-primary">Thêm tài liệu</button></div></form></Dialog>}
 {modal==='survey'&&<Dialog title="Tạo form khảo sát" onClose={()=>setModal(null)}><form onSubmit={saveSurvey} className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setSv({...sv,form_type:'end_session'})} className={`rounded-xl border p-4 text-left ${sv.form_type==='end_session'?'border-cyan-600 bg-cyan-50':'border-slate-200'}`}><ClipboardList className="h-6 w-6 text-cyan-700"/><b className="mt-3 block">Tạo phiếu khảo sát cuối buổi</b></button><button type="button" onClick={()=>setSv({...sv,form_type:'end_course'})} className={`rounded-xl border p-4 text-left ${sv.form_type==='end_course'?'border-cyan-600 bg-cyan-50':'border-slate-200'}`}><CheckCircle2 className="h-6 w-6 text-cyan-700"/><b className="mt-3 block">Tạo bài đánh giá cuối khóa tập huấn</b></button></div><Input label="Tên form *" required value={sv.title} onChange={e=>setSv({...sv,title:e.target.value})}/><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-bold">Buổi tập huấn</span><select value={sv.session} onChange={e=>setSv({...sv,session:e.target.value})} className="w-full rounded-lg border px-3 py-2"><option value="">Chưa gắn buổi</option>{sessions.map(x=><option key={x.id} value={x.id}>{showDate(x.date)} · {x.title}</option>)}</select></label><label><span className="mb-1 block text-sm font-bold">Đối tác</span><select value={sv.partner} onChange={e=>setSv({...sv,partner:e.target.value})} className="w-full rounded-lg border px-3 py-2"><option value="">Chưa gắn đối tác</option>{partners.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label><span className="mb-1 block text-sm font-bold">Ghi chú</span><textarea value={sv.notes} onChange={e=>setSv({...sv,notes:e.target.value})} className="min-h-16 w-full rounded-lg border px-3 py-2"/></label><div className="flex justify-end gap-3"><button type="button" onClick={()=>setModal(null)} className="rounded-lg border px-4 py-2 text-sm font-bold">Hủy</button><button className="ft-primary">Tạo form</button></div></form></Dialog>}
 {notice&&<div className="fixed bottom-5 right-5 z-[60] flex max-w-md gap-3 rounded-xl border border-cyan-200 bg-white p-4 shadow-xl"><p className="text-sm font-semibold">{notice}</p><button onClick={()=>setNotice('')} className="text-sm font-bold text-slate-500">Đóng</button></div>}
 </div></main></div>
}
