import React, { useMemo, useState } from 'react';
import type { ExamPaper } from './ExamPapers';

type Props = { idToken?: string | null; paper: ExamPaper; onChange: (paper: ExamPaper) => void; onNotice: (message: string) => void };

export default function PaperWorkflowPanel(props: Props) {
  const { idToken, paper, onChange, onNotice } = props;
  const [busy,setBusy]=useState(false),[scope,setScope]=useState('QUESTION'),[questionId,setQuestionId]=useState(''),[verdict,setVerdict]=useState('PASSED'),[notes,setNotes]=useState('');
  const stages=[['DRAFT','Nháp'],['AI_REVIEW','AI kiểm tra'],['STAFF_PRECHECK','Chờ nhân viên kiểm tra'],['DRAFT_EXPORTED','Chờ phản biện'],['PEER_REVIEW','Đang phản biện'],['AWAITING_APPROVAL','Chờ phê duyệt'],['APPROVED','Đã phê duyệt'],['OFFICIAL','Hoàn thành'],['BANKED','Đã lưu ngân hàng'],['ARCHIVED','Lưu trữ']];
  const current=Math.max(0,stages.findIndex(item=>item[0]===paper.status)),report=paper.qualityReport||{};
  const latestQuestions=useMemo(()=>new Map<string,any>((paper.reviews||[]).filter(item=>item.scope==='QUESTION').slice().reverse().map(item=>[item.questionId,item] as [string,any])),[paper.reviews]);
  const post=async(path:string,body:unknown)=>{setBusy(true);try{const response=await fetch(`/api/examination${path}`,{method:'POST',headers:{Authorization:`Bearer ${idToken||''}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Không thể cập nhật quy trình.');onChange(data);return true}catch(error:any){onNotice(error.message);return false}finally{setBusy(false)}};
  const transition=async(action:string,message:string)=>{if(await post(`/papers/${paper.id}/transition`,{action}))onNotice(message)};
  const submitReview=async()=>{if(scope==='QUESTION'&&!questionId){onNotice('Hãy chọn câu cần phản biện.');return}if(await post(`/papers/${paper.id}/reviews`,{scope,questionId,verdict,notes})){setNotes('');onNotice(verdict==='PASSED'?'Đã ghi nhận phản biện đạt.':'Đã yêu cầu chỉnh sửa đề.')}};
  const h=React.createElement;
  const stageNodes=stages.map((item,index)=>h('div',{key:item[0],className:`rounded-lg border p-2 text-xs font-bold ${index===current?'border-[#0055da] bg-blue-50 text-[#003d9e]':index<current?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-slate-200 text-slate-400'}`},`${index<current?'✓ ':'○ '}${item[1]}`));
  const actions:any[]=[];
  const addAction=(status:string,action:string,label:string,message:string)=>{if(paper.status===status)actions.push(h('button',{key:action,disabled:busy,onClick:()=>transition(action,message),className:'ft-primary disabled:opacity-50'},label))};
  addAction('STAFF_PRECHECK','confirm_staff_precheck','Xác nhận kiểm tra & lưu đề nháp','Đã xác nhận kiểm tra sơ bộ và lưu đề nháp.');
  addAction('DRAFT_EXPORTED','start_peer_review','Bắt đầu phản biện','Đã chuyển đề sang phản biện.');
  addAction('PEER_REVIEW','submit_approval','Gửi phê duyệt','Đã gửi đề chờ phê duyệt.');
  addAction('AWAITING_APPROVAL','approve','Phê duyệt đề','Đề đã được phê duyệt trên hệ thống.');
  addAction('APPROVED','mark_official_export','Chuyển sang đề chính thức','Đã mở bước xuất đề chính thức.');
  addAction('OFFICIAL','bank','Lưu vào ngân hàng','Đã lưu đề vào ngân hàng.');
  addAction('BANKED','archive','Lưu trữ đề','Đã chuyển đề vào lưu trữ.');
  const answerText=Object.entries(report.answerDistribution||{}).map(([key,value])=>`${key}: ${value}`).join(' · ')||'—';
  const quality=Object.keys(report).length?h('div',{className:`mt-4 rounded-xl border p-4 text-sm ${report.passed?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`},h('b',null,report.passed?'Kiểm tra kỹ thuật đạt':'Kiểm tra kỹ thuật còn lỗi'),h('p',{className:'mt-1'},`Phân bố đáp án: ${answerText} · Chuỗi giống nhau dài nhất: ${report.maxAnswerRun||0}`),...(report.issues||[]).map((issue:string)=>h('p',{key:issue,className:'mt-1 text-amber-800'},`• ${issue}`))):null;
  let reviewForm=null;
  if(paper.status==='PEER_REVIEW')reviewForm=h('div',{className:'mt-5 rounded-xl border border-slate-200 p-4'},h('h3',{className:'font-extrabold text-[#001e40]'},'Ghi nhận phản biện'),h('div',{className:'mt-3 grid gap-3 md:grid-cols-3'},h('select',{value:scope,onChange:(event:any)=>setScope(event.target.value),className:'ft-input'},h('option',{value:'QUESTION'},'Phản biện câu'),h('option',{value:'PAPER'},'Phản biện đề')),scope==='QUESTION'?h('select',{value:questionId,onChange:(event:any)=>setQuestionId(event.target.value),className:'ft-input'},h('option',{value:''},'Chọn câu'),...(paper.questions||[]).map(question=>h('option',{key:question.id,value:question.id},`Câu ${question.order} ${latestQuestions.get(question.id||'')?.verdict==='PASSED'?'✓':''}`))):h('div',{className:'rounded-lg bg-slate-50 p-3 text-sm'},'Đánh giá tính nhất quán của toàn bộ đề'),h('select',{value:verdict,onChange:(event:any)=>setVerdict(event.target.value),className:'ft-input'},h('option',{value:'PASSED'},'Đạt'),h('option',{value:'REVISION_REQUIRED'},'Yêu cầu chỉnh sửa'))),h('textarea',{value:notes,onChange:(event:any)=>setNotes(event.target.value),className:'ft-input mt-3 min-h-20',placeholder:scope==='QUESTION'?'Kiểm tra logic, đáp án, dữ kiện, diễn đạt…':'Kiểm tra tính nhất quán toàn đề, phân bố, thời lượng, độ phủ ma trận…'}),h('button',{disabled:busy,onClick:submitReview,className:'mt-3 rounded-lg border border-[#0055da] px-4 py-2 text-sm font-bold text-[#0055da]'},'Lưu phản biện'));
  return h('section',{className:'rounded-2xl border border-slate-200 bg-white p-5 shadow-sm'},h('h2',{className:'font-extrabold text-[#001e40]'},'Quy trình đề thi'),h('p',{className:'mt-1 text-sm text-slate-500'},'Ma trận → sinh đề → AI kiểm tra → nhân viên kiểm tra → lưu nháp → phản biện → phê duyệt → hoàn thành → ngân hàng.'),h('div',{className:'mt-4 grid gap-2 sm:grid-cols-3 xl:grid-cols-10'},...stageNodes),paper.status==='NEEDS_REVISION'?h('p',{className:'mt-4 rounded-lg bg-rose-50 p-3 text-sm font-bold text-rose-700'},'Phản biện yêu cầu chỉnh sửa. Lưu thay đổi sẽ đưa đề về bước Nháp để kiểm tra lại.'):null,paper.status==='ARCHIVED'?h('p',{className:'mt-4 rounded-lg bg-slate-100 p-3 text-sm font-bold text-slate-700'},'Đề đã được lưu trữ và giữ nguyên lịch sử xử lý.'):null,quality,h('div',{className:'mt-4 flex flex-wrap gap-2'},...actions),reviewForm);
}
