import React,{useMemo,useState}from'react';
import{CalendarDays,Plus,X}from'lucide-react';
import type{Candidate}from'./types';
type Lesson={date:string;label:string}; type Course={id:string;name:string;subject:string;teacher:string;start:string;end:string;days:number[];startTime:string;endTime:string;note:string;mode:'Trực tiếp'|'Trực tuyến';link:string};
const seed:Course={id:'imo-3',name:'IMO - 3',subject:'Toán Olympic',teacher:'Nguyễn Hoàng Long',start:'2026-07-06',end:'2026-08-08',days:[1,4],startTime:'18:00',endTime:'19:30',note:'Dành cho học sinh khối 5, 6.',mode:'Trực tiếp',link:''};
const makeLessons=(c:Course):Lesson[]=>{const a=new Date(c.start+'T00:00:00'),b=new Date(c.end+'T00:00:00'),out:Lesson[]=[];for(let d=new Date(a);d<=b&&out.length<30;d.setDate(d.getDate()+1))if(c.days.includes(d.getDay()))out.push({date:d.toISOString().slice(0,10),label:'Buổi '+(out.length+1)+' · '+d.toLocaleDateString('vi-VN',{weekday:'short',day:'2-digit',month:'2-digit'})});return out};
export default function TrainingClasses({candidates,onCandidate}:{candidates:Candidate[];onCandidate:(c:Candidate)=>void}){
 const[courses,setCourses]=useState<Course[]>([seed]),[selected,setSelected]=useState<Course|null>(null),[show,setShow]=useState(false),[tab,setTab]=useState<'info'|'students'|'attendance'>('info'),[attendance,setAttendance]=useState<Record<string,Record<string,string>>>({});
 const empty=()=>({...seed,id:'course-'+Date.now(),name:'',subject:'',teacher:'',start:'',end:'',days:[],note:'',mode:'Trực tiếp' as const,link:''}); const[draft,setDraft]=useState<Course>(empty());
 const create=()=>{if(!draft.name||!draft.subject||!draft.teacher||!draft.start||!draft.end||!draft.days.length)return;setCourses(x=>[...x,draft]);setShow(false);setSelected(draft)};
 const status=(date:string,code:string)=>attendance[date]?.[code]||'Chưa điểm danh';
 const mark=(date:string,code:string)=>setAttendance(x=>({...x,[date]:{...x[date],[code]:status(date,code)==='Có mặt'?'Vắng có phép':status(date,code)==='Vắng có phép'?'Vắng':'Có mặt'}}));
 if(selected){const lessons=makeLessons(selected),button=(id:typeof tab,label:string)=><button onClick={()=>setTab(id)} className={`border-b-2 pb-2 text-sm font-bold ${tab===id?'border-[#aa3000] text-[#aa3000]':'border-transparent text-slate-600'}`}>{label}</button>;return <><button onClick={()=>setSelected(null)} className="mb-4 text-sm font-bold text-slate-600">← Quay lại các lớp ôn tập</button><section className="ft-surface"><p className="text-sm font-bold text-[#aa3000]">LỚP ÔN TẬP</p><h1 className="mt-1 text-3xl font-extrabold">{selected.name}</h1><p className="mt-2 text-sm text-slate-600">{selected.subject} · {selected.teacher} · {selected.startTime}–{selected.endTime}</p><div className="mt-6 flex gap-5 border-t pt-4">{button('info','Thông tin lớp học')}{button('students','Danh sách học sinh')}{button('attendance','Danh sách điểm danh')}</div></section>{tab==='info'&&<section className="mt-6 ft-surface"><h2 className="text-xl font-bold">Lịch học và thời hạn</h2><p className="mt-2 text-sm text-slate-600">{selected.start} đến {selected.end} · {lessons.length} buổi học</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{lessons.map(l=><div key={l.date} className="rounded-lg border p-3 text-sm"><b>{l.label}</b><p className="mt-1 text-slate-500">{selected.startTime}–{selected.endTime}</p></div>)}</div><p className="mt-4 text-sm">{selected.mode}{selected.link&&' · '+selected.link}<br/>{selected.note}</p></section>}{tab==='students'&&<section className="mt-6 ft-surface"><h2 className="mb-4 text-xl font-bold">Danh sách học sinh</h2><table className="ft-table"><thead><tr><th>Học sinh</th><th>Trường học</th><th>Cuộc thi</th></tr></thead><tbody>{candidates.slice(0,2).map(c=><tr key={c.code} onClick={()=>onCandidate(c)} className="cursor-pointer hover:bg-blue-50/50"><td><b>{c.name}</b><p className="text-xs">{c.code}</p></td><td>{c.school}</td><td>{c.contests}</td></tr>)}</tbody></table></section>}{tab==='attendance'&&<section className="mt-6 ft-surface overflow-hidden"><h2 className="mb-1 text-xl font-bold">Danh sách điểm danh theo buổi</h2><p className="mb-4 text-sm text-slate-500">Chọn buổi học thực tế; lịch có thể thay đổi bằng cách thêm/sửa buổi trong lớp.</p><div className="overflow-x-auto"><table className="ft-table min-w-[900px]"><thead><tr><th>Học sinh</th>{lessons.map(l=><th key={l.date} className="whitespace-nowrap">{l.label}</th>)}</tr></thead><tbody>{candidates.slice(0,2).map(c=><tr key={c.code}><td><b>{c.name}</b></td>{lessons.map(l=><td key={l.date}><button onClick={()=>mark(l.date,c.code)} className="whitespace-nowrap rounded bg-slate-100 px-2 py-1 text-xs font-bold">{status(l.date,c.code)}</button></td>)}</tr>)}</tbody></table></div></section>}</>}
 return <><div className="mb-6 flex justify-end"><button onClick={()=>{setDraft(empty());setShow(true)}} className="ft-primary"><Plus className="h-4 w-4"/>Tạo lớp mới</button></div><div className="grid gap-5 lg:grid-cols-3">{courses.map(c=><button key={c.id} onClick={()=>{setSelected(c);setTab('info')}} className="ft-surface text-left"><CalendarDays className="h-7 w-7"/><h2 className="mt-4 text-lg font-bold">{c.name}</h2><p className="mt-2 text-sm">Giáo viên: {c.teacher}</p><p className="text-sm">Lịch: {makeLessons(c).length} buổi · {c.startTime}</p></button>)}</div>{show&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4"><div className="w-full max-w-2xl rounded-xl bg-white p-6"><button onClick={()=>setShow(false)} className="float-right"><X/></button><h2 className="text-2xl font-bold">Tạo lớp ôn tập mới</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{([['name','Tên lớp'],['subject','Môn học'],['teacher','Giáo viên'],['start','Ngày bắt đầu'],['end','Ngày kết thúc'],['startTime','Giờ bắt đầu'],['endTime','Giờ kết thúc']]as[keyof Course,string][]).map(([key,label])=><label key={key}>{label}<input type={key==='start'||key==='end'?'date':'text'} value={String(draft[key])} onChange={e=>setDraft({...draft,[key]:e.target.value})} className="mt-1 w-full rounded border px-3 py-2"/></label>)}</div><div className="mt-4"><b className="text-sm">Ngày học hằng tuần</b><div className="mt-2 flex flex-wrap gap-3">{['CN','T2','T3','T4','T5','T6','T7'].map((d,i)=><label key={d}><input type="checkbox" checked={draft.days.includes(i)} onChange={()=>setDraft({...draft,days:draft.days.includes(i)?draft.days.filter(x=>x!==i):[...draft.days,i]})}/> {d}</label>)}</div></div><div className="mt-4 flex gap-4"><label><input type="radio" checked={draft.mode==='Trực tiếp'} onChange={()=>setDraft({...draft,mode:'Trực tiếp'})}/> Trực tiếp</label><label><input type="radio" checked={draft.mode==='Trực tuyến'} onChange={()=>setDraft({...draft,mode:'Trực tuyến'})}/> Trực tuyến</label></div>{draft.mode==='Trực tuyến'&&<label className="mt-3 block">Link học<input value={draft.link} onChange={e=>setDraft({...draft,link:e.target.value})} className="mt-1 w-full rounded border px-3 py-2"/></label>}<label className="mt-3 block">Ghi chú<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} className="mt-1 w-full rounded border px-3 py-2"/></label><div className="mt-5 flex justify-end"><button onClick={create} className="ft-primary">Tạo lớp và sinh lịch</button></div></div></div>}</>}
