# Generated by Django 5.0.14 on 2026-07-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contract_start', models.CharField(blank=True, max_length=20)),
                ('contract_end', models.CharField(blank=True, max_length=20)),
                ('training_content', models.TextField(blank=True)),
                ('planned_sessions', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['session_date', 'start_time', 'title']},
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('planned', 'Đã lên lịch'), ('completed', 'Đã thực hiện'), ('cancelled', 'Đã hủy')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='digital-training/materials/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='digital_training.trainingsession')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='digital_training.trainingpartner')),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='partner_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='digital_training.trainingpartner'),
        ),
        migrations.CreateModel(
            name='TrainingSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('form_type', models.CharField(choices=[('end_session', 'Phiếu khảo sát cuối buổi'), ('end_course', 'Bài đánh giá cuối khóa tập huấn')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='digital_training.trainingpartner')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='digital_training.trainingsession')),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
            },
        ),
    ]
