# Generated by Django 5.0.14 on 2026-07-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0002_trainingpartner_alter_trainingsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='contents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
