# Generated by Django 5.0.14 on 2026-07-28 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0003_trainingsession_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('members', models.CharField(blank=True, max_length=500)),
                ('planned_sessions', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='digital_training.trainingpartner')),
            ],
            options={
                'ordering': ['partner__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='digital_training.trainingclass'),
        ),
        migrations.AddConstraint(
            model_name='trainingclass',
            constraint=models.UniqueConstraint(fields=('partner', 'name'), name='unique_training_class_per_partner'),
        ),
    ]
