# Generated by Django 5.0.14 on 2026-07-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0005_seed_training_partner_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
