# Generated by Django 5.0.14 on 2026-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0007_populate_training_session_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='ai_account_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='contract_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='contract_duration_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='contract_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='contract_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='partner_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='training_contents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='training_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('planned', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsurvey',
            name='form_type',
            field=models.CharField(choices=[('end_session', 'End session'), ('end_course', 'End course')], max_length=20),
        ),
    ]
