# Generated by Django 5.0.14 on 2026-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0009_clear_existing_training_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
