# Generated by Django 5.0.14 on 2026-07-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0010_trainingpartner_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='additional_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
