# Generated by Django 5.0.14 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0011_trainingpartner_additional_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='training_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='training_staff',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='staff_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('planned', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]