# Generated by Django 5.0.14 on 2026-07-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0012_training_location_staff_and_unscheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCustomerMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('customer_type', models.CharField(blank=True, max_length=100)),
                ('representative', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['meeting_date', 'start_time', 'title'],
            },
        ),
    ]
