# Generated by Django 5.0.14 on 2026-07-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0013_trainingcustomermeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcustomermeeting',
            name='staff_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingcustomermeeting',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('planned', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
