# Generated by Django 5.0.14 on 2026-07-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0014_trainingcustomermeeting_staff_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcustomermeeting',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingcustomermeeting',
            name='schedule_type',
            field=models.CharField(choices=[('meeting', 'Customer meeting'), ('other', 'Other work activity')], default='meeting', max_length=20),
        ),
    ]
