# Generated by Django 5.0.14 on 2026-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0016_distribute_shared_sessions_to_classes'),
    ]

    def normalize_partner_types(apps, schema_editor):
        Partner = apps.get_model('digital_training', 'TrainingPartner')
        Partner.objects.filter(partner_type='Khối hành chính công').update(partner_type='Khối Hành chính công')

    operations = [
        migrations.AddField(
            model_name='trainingpartner',
            name='contact_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='partner_subtype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(normalize_partner_types, migrations.RunPython.noop),
    ]
