# Generated by FT Workspace on 2026-07-29

from datetime import date

from django.db import migrations


def complete_past_scheduled_sessions(apps, schema_editor):
    Session = apps.get_model("digital_training", "TrainingSession")
    Session.objects.filter(status="planned", session_date__lt=date.today()).update(status="completed")


class Migration(migrations.Migration):
    dependencies = [
        ("digital_training", "0017_trainingpartner_contact_position_and_more"),
    ]

    operations = [
        migrations.RunPython(complete_past_scheduled_sessions, migrations.RunPython.noop),
    ]
