# Generated by Django 5.0.14 on 2026-07-29 09:17

from django.db import migrations, models


def populate_class_training_contents(apps, schema_editor):
    TrainingClass = apps.get_model('digital_training', 'TrainingClass')
    TrainingSession = apps.get_model('digital_training', 'TrainingSession')
    for training_class in TrainingClass.objects.select_related('partner').all():
        contents = next(
            (
                value
                for value in TrainingSession.objects.filter(training_class_id=training_class.id)
                .order_by('session_number', 'id')
                .values_list('contents', flat=True)
                if isinstance(value, list) and value
            ),
            training_class.partner.training_contents or [],
        )
        if contents:
            TrainingClass.objects.filter(pk=training_class.pk).update(training_contents=contents)

class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0018_complete_past_scheduled_training_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclass',
            name='training_contents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingpartner',
            name='ward',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_class_training_contents, migrations.RunPython.noop),
    ]
