# Generated by Django 5.0.14 on 2026-08-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0021_trainingassessment_generation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassessment',
            name='audience_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingassessment',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingassessment',
            name='max_people_per_variant',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='trainingassessment',
            name='output_sheet_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingassessment',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingassessment',
            name='question_bank_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingassessment',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingassessment',
            name='sync_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingassessmentattempt',
            name='participant_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingassessmentattempt',
            name='practical_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingassessmentattempt',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trainingassessmentattempt',
            name='purge_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingassessmentattempt',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingassessmentattempt',
            name='sync_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingassessmentattempt',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
