# Generated by Django 5.0.14 on 2026-08-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0022_trainingassessment_audience_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassessmentupload',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingassessmentupload',
            name='drive_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingassessmentupload',
            name='sync_status',
            field=models.CharField(default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingassessmentupload',
            name='file',
            field=models.FileField(blank=True, upload_to='digital-training/assessment-answers/%Y/%m/'),
        ),
    ]
