# Generated by Django 5.0.14 on 2026-08-01 03:53

import django.db.models.deletion
from calendar import monthrange
from django.db import migrations, models


def add_duration(start, amount, unit):
    if not start or not amount:
        return None
    if unit == 'year':
        year = start.year + amount
        return start.replace(year=year, day=min(start.day, monthrange(year, start.month)[1]))
    month_index = start.month - 1 + amount
    year = start.year + month_index // 12
    month = month_index % 12 + 1
    return start.replace(year=year, month=month, day=min(start.day, monthrange(year, month)[1]))


def seed_products_and_subscriptions(apps, schema_editor):
    Product = apps.get_model('digital_training', 'TrainingProduct')
    Subscription = apps.get_model('digital_training', 'TrainingProductSubscription')
    Partner = apps.get_model('digital_training', 'TrainingPartner')
    definitions = [
        ('BNDC', 'bndc', 'Nền tảng/không gian dữ liệu dùng chung', 1),
        ('AI dùng chung', 'ai-dung-chung', 'Tài khoản AI bản quyền dùng chung', 2),
        ('Lớp học số', 'lop-hoc-so', 'Lớp học số hoặc trường học số', 3),
    ]
    products = {}
    for name, code, description, order in definitions:
        products[code] = Product.objects.create(name=name, code=code, description=description, display_order=order)

    def selected(values, *needles):
        source = ' | '.join(str(value or '').strip().casefold() for value in values or [])
        return any(needle in source for needle in needles)

    for partner in Partner.objects.all():
        legacy = partner.products or []
        selected_codes = []
        if selected(legacy, 'bndc', 'không gian dữ liệu dùng chung'):
            selected_codes.append('bndc')
        if selected(legacy, 'ai dùng chung', 'ai có bản quyền dùng chung') or partner.ai_account_count:
            selected_codes.append('ai-dung-chung')
        if selected(legacy, 'lớp học số', 'trường học số'):
            selected_codes.append('lop-hoc-so')
        expires_at = add_duration(partner.contract_signed_date, partner.contract_duration, partner.contract_duration_unit or 'month')
        for code in selected_codes:
            quantity = partner.ai_account_count if code == 'ai-dung-chung' and partner.ai_account_count else 1
            Subscription.objects.get_or_create(
                partner=partner,
                product=products[code],
                defaults={
                    'quantity': quantity,
                    'starts_at': partner.contract_signed_date,
                    'expires_at': expires_at,
                    'status': 'active',
                    'notes': 'Tự động nhập từ dữ liệu khách hàng hiện có.',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0023_trainingassessmentupload_drive_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProductSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subscriptions', to='digital_training.trainingpartner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='digital_training.trainingproduct')),
            ],
            options={
                'ordering': ['partner__name', 'product__display_order', 'product__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingproductsubscription',
            constraint=models.UniqueConstraint(fields=('partner', 'product'), name='unique_product_subscription_per_partner'),
        ),
        migrations.RunPython(seed_products_and_subscriptions, migrations.RunPython.noop),
    ]
