# Generated by Django 5.0.14 on 2026-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0024_trainingproduct_trainingproductsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingproduct',
            name='product_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
    ]
