# Generated by Django 5.0.14 on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_training", "0025_trainingproduct_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingFinanceEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_date", models.DateField()),
                ("entry_type", models.CharField(choices=[("income", "Income"), ("expense", "Expense")], max_length=20)),
                ("category", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=500)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=16)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("overdue", "Overdue"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("payment_method", models.CharField(blank=True, max_length=100)),
                ("reference_code", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.EmailField(blank=True, max_length=254)),
                ("updated_by", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("partner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="finance_entries", to="digital_training.trainingpartner")),
            ],
            options={"ordering": ["-transaction_date", "-id"]},
        ),
    ]
