# Generated by Django 5.0.14 on 2026-08-04 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_training', '0027_trainingassessment_storage_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lead_type', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('representative', models.CharField(blank=True, max_length=255)),
                ('representative_position', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('stage', models.CharField(choices=[('discussion', 'Discussion'), ('meeting', 'Meeting'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('on_hold', 'On hold'), ('lost', 'Lost'), ('converted', 'Converted')], default='discussion', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='digital_training.trainingpartner')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='trainingcustomermeeting',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='digital_training.traininglead'),
        ),
    ]
