# Generated by Django 5.0.14 on 2026-07-30 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0010_seed_default_departments_and_copy_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('shift_code', models.CharField(max_length=30)),
                ('shift_name', models.CharField(max_length=120)),
                ('scheduled_start', models.TimeField()),
                ('scheduled_end', models.TimeField()),
                ('expected_minutes', models.PositiveIntegerField(default=480)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('clock_in_ip', models.CharField(blank=True, default='', max_length=64)),
                ('clock_out_ip', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='authentication.userprofile')),
            ],
            options={
                'ordering': ['-work_date', '-clock_in'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='attendance_employee_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date', 'shift_code'), name='unique_employee_daily_shift'),
        ),
    ]
