# Generated by Django 5.0.14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('authentication', '0010_seed_default_departments_and_copy_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('shift_number', models.PositiveSmallIntegerField(default=1)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('work_mode', models.CharField(choices=[('direct', 'Trực tiếp'), ('online', 'Online')], default='direct', max_length=10)),
                ('is_day_off', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='authentication.userprofile')),
            ],
            options={
                'ordering': ['-work_date', 'shift_number'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='timesheet_employee_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date', 'shift_number'), name='unique_employee_date_shift'),
        ),
    ]
