# Generated by Django 5.0.14 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, default="", max_length=1000)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("blocks", models.JSONField(blank=True, default=list)),
                ("last_updated", models.BigIntegerField()),
                ("created_by", models.CharField(max_length=255)),
                ("updated_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailUserPref",
            fields=[
                (
                    "email",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "active_template_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("left_panel_width", models.IntegerField(default=152)),
                ("right_panel_width", models.IntegerField(default=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
