# Generated by Django 5.2 for FT Workspace.
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("authentication", "0011_add_default_workspace_module_access")]

    operations = [
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("work_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("todo", "Cần làm"), ("doing", "Đang thực hiện"), ("completed", "Đã hoàn thành"), ("reviewed", "Đã review")], db_index=True, default="todo", max_length=20)),
                ("priority", models.CharField(choices=[("low", "Thấp"), ("medium", "Vừa"), ("high", "Cao")], default="medium", max_length=20)),
                ("label", models.CharField(blank=True, default="Công việc", max_length=100)),
                ("needs_revision", models.BooleanField(default=False)),
                ("revision_count", models.PositiveIntegerField(default=0)),
                ("review_percent", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("review_note", models.CharField(blank=True, default="", max_length=1000)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="created_work_items", to="authentication.userprofile")),
                ("executor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assigned_work_items", to="authentication.userprofile")),
                ("managers", models.ManyToManyField(blank=True, related_name="managed_work_items", to="authentication.userprofile")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_work_items", to="authentication.userprofile")),
                ("supporters", models.ManyToManyField(blank=True, related_name="supported_work_items", to="authentication.userprofile")),
            ],
            options={"ordering": ["work_date", "start_time", "created_at"]},
        ),
        migrations.AddIndex(model_name="workitem", index=models.Index(fields=["executor", "work_date", "status"], name="work_executor_date_status_idx")),
        migrations.AddIndex(model_name="workitem", index=models.Index(fields=["creator", "work_date"], name="work_creator_date_idx")),
        migrations.RunSQL("PRAGMA optimize", reverse_sql=migrations.RunSQL.noop),
    ]
