# Generated by Django 5.0.14 on 2026-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedule', '0010_finalize_phong_sheet_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScheduleSheetInboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('processed', 'Đã xử lý'), ('failed', 'Lỗi')], db_index=True, max_length=20)),
                ('created_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_count', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
