# Generated by Django 5.0.14 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("school", models.CharField(blank=True, max_length=255, null=True)),
                ("class_name", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("contests", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "achievement",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("parent", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("identity", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=1000, null=True)),
                ("birth_date", models.CharField(blank=True, max_length=100, null=True)),
                ("session_ids", models.JSONField(blank=True, default=list)),
                ("sort_key", models.CharField(max_length=255)),
                ("updated", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("parent", models.CharField(max_length=100)),
                ("organizer", models.CharField(max_length=255)),
                ("sort_key", models.CharField(max_length=255)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExaminationSheet",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=1000)),
                ("status", models.CharField(default="idle", max_length=50)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("competition_id", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("parent", models.CharField(max_length=100)),
                ("organizer", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=100)),
                ("candidates_count", models.IntegerField(default=0)),
                ("national", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "national_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "international",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "international_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phase", models.CharField(default="Chuẩn bị", max_length=50)),
                ("note", models.TextField(blank=True, null=True)),
                ("rounds", models.JSONField(blank=True, default=list)),
                ("sort_key", models.CharField(max_length=255)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LogNote",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
