# Generated by Django 5.0.14 on 2026-07-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_lognote_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='exam_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
