# Generated by Django 5.0.14 on 2026-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_candidate_exam_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationsheet',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examinationsheet',
            name='sheet_tab',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examinationsheet',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
