# Generated by Django 5.0.14 on 2026-07-22 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_rename_sco_competition_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='', max_length=1000)),
                ('registration_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='examination.candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='examination.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=255)),
                ('sbd', models.CharField(blank=True, default='', max_length=255)),
                ('exam_date', models.CharField(blank=True, default='', max_length=255)),
                ('time_slot', models.CharField(blank=True, default='', max_length=255)),
                ('mode', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=1000)),
                ('link', models.CharField(blank=True, default='', max_length=2000)),
                ('account', models.CharField(blank=True, default='', max_length=1000)),
                ('attendance', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.CharField(blank=True, default='', max_length=255)),
                ('score_rate', models.CharField(blank=True, default='', max_length=255)),
                ('rank', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(blank=True, default='', max_length=1000)),
                ('note', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='examination.candidateparticipation')),
            ],
            options={
                'ordering': ['round_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidateparticipation',
            constraint=models.UniqueConstraint(fields=('candidate', 'session'), name='unique_candidate_participation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='roundresult',
            constraint=models.UniqueConstraint(fields=('participation', 'round_name'), name='unique_round_per_participation'),
        ),
    ]
