# Generated by Django 5.0.14 on 2026-07-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0007_migrate_legacy_candidate_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='certificate_link',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='exam_language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='general_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='registration_method',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='registration_unit',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='eligibility',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
