# Generated by Django 5.0.14 on 2026-07-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_candidate_grade_candidate_nationality_candidate_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='highest_round',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
