# Generated by Django 5.0.14 on 2026-07-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_candidate_highest_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresult',
            name='password',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
