# Generated by Django 5.0.14 on 2026-07-26 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0010_roundresult_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True, default='https://api.openai.com/v1')),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('generation_model', models.CharField(blank=True, default='gpt-4.1-mini', max_length=255)),
                ('review_model', models.CharField(blank=True, default='gpt-4.1-mini', max_length=255)),
                ('temperature', models.FloatField(default=0.4)),
                ('max_tokens', models.PositiveIntegerField(default=12000)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('grade_or_category', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(default='Tiếng Việt', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('difficulty_distribution', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('READY', 'Sẵn sàng'), ('REVIEW', 'Cần kiểm tra'), ('ARCHIVED', 'Lưu trữ')], default='DRAFT', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('ai_generation_status', models.CharField(blank=True, default='idle', max_length=30)),
                ('ai_generation_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='examination.competition')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='examination.examsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
                ('task_type', models.CharField(max_length=100)),
                ('provider', models.CharField(default='openai', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='examination.exampaper')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=10)),
                ('explanation', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Trung bình'), ('HARD', 'Khó'), ('VERY_HARD', 'Rất khó')], default='MEDIUM', max_length=20)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('check_status', models.CharField(choices=[('PENDING', 'Chưa kiểm tra'), ('PASSED', 'Đạt yêu cầu'), ('AI_FIXED', 'Đã được AI chỉnh sửa'), ('NEEDS_REVIEW', 'Cần người dùng kiểm tra'), ('WARNING', 'Có cảnh báo')], default='PENDING', max_length=30)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examination.exampaper')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('UPLOAD', 'Tệp tải lên'), ('PAPER', 'Đề trong kho'), ('SYLLABUS', 'Syllabus'), ('DESCRIPTION', 'Mô tả')], max_length=30)),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam-paper-sources/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='examination.exampaper')),
                ('referenced_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_source_by', to='examination.exampaper')),
            ],
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('paper', 'order'), name='unique_question_order_per_paper'),
        ),
    ]
