# Generated by Django 5.0.14 on 2026-07-27 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0013_import_ft_contest_plan_2026_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Trắc nghiệm một đáp án'), ('numeric_input', 'Điền đáp số')], default='single_choice', max_length=40)),
                ('option_count', models.PositiveSmallIntegerField(default=4)),
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('difficulty', models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Trung bình'), ('HARD', 'Khó'), ('VERY_HARD', 'Rất khó')], default='MEDIUM', max_length=20)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('knowledge_source', models.CharField(blank=True, default='', max_length=500)),
                ('knowledge_requirements', models.TextField(blank=True, default='')),
                ('prohibited_knowledge', models.TextField(blank=True, default='')),
                ('assessment_intent', models.TextField(blank=True, default='')),
                ('estimated_seconds', models.PositiveIntegerField(default=90)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(default='single_choice', max_length=40),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='slot_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('round_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('grade_or_category', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(default='Tiếng Việt', max_length=50)),
                ('metadata_schema', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='examination.competition')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='examination.examsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='blueprint_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='examination.blueprintslot'),
        ),
        migrations.CreateModel(
            name='BlueprintVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('LOCKED', 'Đã khóa'), ('ARCHIVED', 'Lưu trữ')], default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('locked_by', models.CharField(blank=True, default='', max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='examination.blueprint')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='blueprintslot',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='examination.blueprintversion'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='blueprint_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_papers', to='examination.blueprintversion'),
        ),
        migrations.CreateModel(
            name='ExamGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Đang chờ'), ('GENERATING', 'Đang sinh'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Lỗi')], default='QUEUED', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='examination.blueprintversion')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='examination.exampaper')),
            ],
        ),
        migrations.AddConstraint(
            model_name='blueprintversion',
            constraint=models.UniqueConstraint(fields=('blueprint', 'version_number'), name='unique_blueprint_version_number'),
        ),
        migrations.AddConstraint(
            model_name='blueprintslot',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='unique_blueprint_slot_position'),
        ),
    ]
