# Generated by Django 5.0.14 on 2026-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0015_seed_fimo_grade7_blueprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationSheetPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_url', models.CharField(blank=True, default='', max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='idle', max_length=30)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheets publication',
                'verbose_name_plural': 'Google Sheets publications',
            },
        ),
    ]
