# Generated by Django 5.0.14 on 2026-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0016_sheet_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationsheetpublication',
            name='academic_year',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='registration_sheet_tab',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='examsession',
            name='registration_sheet_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
