# Generated by Django 5.0.14 on 2026-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0018_normalize_multi_day_round_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
