# Generated by Django 5.0.14 on 2026-07-30 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


def normalize_legacy_paper_statuses(apps, schema_editor):
    ExamPaper = apps.get_model('examination', 'ExamPaper')
    ExamPaper.objects.filter(status='READY').update(status='STAFF_PRECHECK')
    ExamPaper.objects.filter(status='REVIEW').update(status='AI_REVIEW')


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0020_normalize_fimo_session_and_blueprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='banked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='draft_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='official_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='quality_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='workflow_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Đề nháp'), ('AI_REVIEW', 'AI kiểm tra sơ bộ'), ('STAFF_PRECHECK', 'Nhân viên kiểm tra sơ bộ'), ('DRAFT_EXPORTED', 'Đã xuất và lưu đề nháp'), ('PEER_REVIEW', 'Đang phản biện'), ('AWAITING_APPROVAL', 'Chờ phê duyệt'), ('APPROVED', 'Đã phê duyệt'), ('OFFICIAL', 'Đề chính thức'), ('BANKED', 'Đã lưu ngân hàng'), ('NEEDS_REVISION', 'Cần chỉnh sửa'), ('ARCHIVED', 'Lưu trữ')], default='DRAFT', max_length=30),
        ),
        migrations.RunPython(normalize_legacy_paper_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ExamReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('QUESTION', 'Phản biện câu'), ('PAPER', 'Phản biện đề')], max_length=20)),
                ('verdict', models.CharField(choices=[('PENDING', 'Chưa kết luận'), ('PASSED', 'Đạt'), ('REVISION_REQUIRED', 'Yêu cầu chỉnh sửa')], default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('reviewer', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='examination.exampaper')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='examination.examquestion')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
