# Generated by Django 5.0.14 on 2026-07-30 07:33

import hashlib
import json
from django.db import migrations, models


def backfill_profiles(apps, schema_editor):
    BlueprintVersion = apps.get_model('examination', 'BlueprintVersion')
    versions = BlueprintVersion.objects.select_related('blueprint', 'blueprint__competition', 'blueprint__session').prefetch_related('slots')
    for version in versions.iterator(chunk_size=100):
        slots = list(version.slots.all())
        difficulty, internal, types, options, topics, sources, signature = {}, {}, {}, {}, {}, {}, []
        total_score = 0.0; total_seconds = 0
        for slot in slots:
            metadata = slot.metadata or {}; label = str(metadata.get('difficultyLabel') or slot.difficulty)
            difficulty[label] = difficulty.get(label, 0) + 1; internal[slot.difficulty] = internal.get(slot.difficulty, 0) + 1
            types[slot.question_type] = types.get(slot.question_type, 0) + 1; option = str(slot.option_count if slot.question_type == 'single_choice' else 0); options[option] = options.get(option, 0) + 1
            topic = slot.topic or 'Chưa phân loại'; topics[topic] = topics.get(topic, 0) + 1; source = slot.knowledge_source or 'Chưa xác định'; sources[source] = sources.get(source, 0) + 1
            total_score += float(slot.score); total_seconds += slot.estimated_seconds
            signature.append([slot.position, slot.question_type, slot.option_count, str(slot.score), label, slot.topic, slot.assessment_intent, metadata])
        blueprint = version.blueprint
        context = {'competitionId':str(blueprint.competition_id or ''),'competitionName':blueprint.competition.name if blueprint.competition else '','sessionId':str(blueprint.session_id or ''),'sessionName':blueprint.session.name if blueprint.session else '','roundName':blueprint.round_name,'subject':blueprint.subject,'gradeOrCategory':blueprint.grade_or_category,'language':blueprint.language,'durationMinutes':blueprint.duration_minutes}
        rules = {'useExactSlotOrder':True,'preserveOriginalDifficultyLabels':True,'preserveQuestionTypesAndOptions':True,'avoidDuplicateQuestions':True,'balanceMultipleChoiceAnswers':True}
        version.analysis = {'parserVersion':'matrix-profile-v2','source':{},'matrixContext':context,'generationRules':rules,'totalQuestions':len(slots),'totalScore':total_score,'estimatedDurationMinutes':max(1,round(total_seconds/60)) if slots else 0,'difficultyDistribution':difficulty,'internalDifficultyDistribution':internal,'questionTypeDistribution':types,'optionCountDistribution':options,'topicDistribution':topics,'knowledgeSourceDistribution':sources,'missingFields':{},'warnings':[],'structureHash':hashlib.sha256(json.dumps(signature,ensure_ascii=False,sort_keys=True).encode('utf-8')).hexdigest()}
        version.save(update_fields=['analysis'])


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0022_backfill_fimo_difficulty_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintversion',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_profiles, migrations.RunPython.noop),
    ]
