# Generated by Django 5.0.14 on 2026-07-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0023_blueprintversion_analysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiproviderconfig',
            options={'ordering': ['priority', 'id']},
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='health_status',
            field=models.CharField(choices=[('UNKNOWN', 'Chưa kiểm tra'), ('READY', 'Sẵn sàng'), ('EXHAUSTED', 'Đã hết hạn mức'), ('ERROR', 'Có lỗi')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='name',
            field=models.CharField(default='Cấu hình AI 1', max_length=255),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='examination.aiproviderconfig'),
        ),
        migrations.AddField(
            model_name='examgenerationjob',
            name='generated_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examgenerationjob',
            name='partial_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='ai_chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider',
            field=models.CharField(db_index=True, default='openai', max_length=100),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('AI_REVIEW', 'AI kiểm tra sơ bộ'), ('STAFF_PRECHECK', 'Chờ nhân viên kiểm tra'), ('DRAFT_EXPORTED', 'Chờ phản biện'), ('PEER_REVIEW', 'Đang phản biện'), ('AWAITING_APPROVAL', 'Chờ phê duyệt'), ('APPROVED', 'Đã phê duyệt'), ('OFFICIAL', 'Hoàn thành'), ('BANKED', 'Đã lưu ngân hàng'), ('NEEDS_REVISION', 'Cần chỉnh sửa'), ('ARCHIVED', 'Lưu trữ')], default='DRAFT', max_length=30),
        ),
    ]
