# Generated by Django 5.0.14 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiLog",
            fields=[
                (
                    "log_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("platform", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=100)),
                ("channel_id", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="running", max_length=50)),
                ("records_received", models.IntegerField(default=0)),
                ("records_inserted", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("request_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("platform", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("external_id", models.CharField(max_length=255)),
                ("status", models.CharField(default="active", max_length=50)),
                ("timezone", models.CharField(default="Asia/Bangkok", max_length=100)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total_posts", models.IntegerField(default=0)),
                ("followers_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DailySnapshot",
            fields=[
                (
                    "snapshot_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("snapshot_date", models.CharField(max_length=50)),
                ("platform", models.CharField(max_length=50)),
                ("channel_id", models.CharField(max_length=255)),
                ("post_key", models.CharField(max_length=255)),
                ("reactions", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("reach", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("total_engagement", models.IntegerField(default=0)),
                ("engagement_rate", models.FloatField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="FollowerSnapshot",
            fields=[
                (
                    "snapshot_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("snapshot_date", models.CharField(max_length=50)),
                ("channel_id", models.CharField(max_length=255)),
                ("channel_name", models.CharField(max_length=255)),
                ("followers_count", models.IntegerField(default=0)),
                ("fetched_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "post_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("platform", models.CharField(max_length=50)),
                ("channel_id", models.CharField(max_length=255)),
                ("external_post_id", models.CharField(max_length=255)),
                ("post_url", models.CharField(max_length=1000)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("post_type", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField()),
                ("imported_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
