# Generated by Django 5.0.14 on 2026-07-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailysnapshot',
            index=models.Index(fields=['channel_id', 'snapshot_date'], name='social_daily_channel_date'),
        ),
        migrations.AddIndex(
            model_name='dailysnapshot',
            index=models.Index(fields=['post_key', 'snapshot_date'], name='social_daily_post_date'),
        ),
        migrations.AddIndex(
            model_name='followersnapshot',
            index=models.Index(fields=['channel_id', 'snapshot_date'], name='social_follow_channel_date'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel_id', 'published_at'], name='social_post_channel_date'),
        ),
    ]
