# Generated by Django 5.0.14 on 2026-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_dailysnapshot_social_daily_channel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followersnapshot',
            name='daily_follows_unique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followersnapshot',
            name='daily_unfollows_unique',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
